language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'
  # '3.3' # not in travis anymore
  # '3.2' # not in travis anymore
  - '2.7'
  # '2.6' # not in travis anymore
  # plasmasm with miasmX works with 2.3, 2.4 and 2.5 too, but they are not available in travis
  # plasmasm with amoco does not work with 2.6
  - 'pypy3'
  - 'pypy'
install:
  - pip install pyparsing
  - pip install tox-travis
  - pip install coverage codecov
  - cd ..
  - git clone https://github.com/LRGH/elfesteem
  - git clone https://github.com/LRGH/miasmX
  - git clone https://github.com/LRGH/crysp
  - git clone https://github.com/LRGH/amoco
  - echo > amoco/amoco/__init__.py # don't import grandalf
  - sed -i -e "s/ 'wait',//" amoco/amoco/arch/x86/parsers.py # bug of amoco
  - cd plasmasm
script:
  # With CPython, not with Pypy, the next command fails when first launched.
  # Probably something to do with pyc generation
  # To be investigated
  - python -c 'from plasmasm import arch; BACKEND = arch.import_cpu_backend("I386", "MIASM")' || true
  # Simple tests to verify that dependencies are working
  - python plasmasm/disass.py -c /MIASM non_regression/basic_x86_linux.intel.s || true
  - python plasmasm/disass.py -c /MIASM non_regression/basic_x86_linux.att.s || true
  - python plasmasm/disass.py -c /MIASM non_regression/basic_x86_linux.o || true
  - python plasmasm/disass.py -c /AMOCO non_regression/basic_x86_linux.att.s || true
  - python plasmasm/disass.py -c /AMOCO non_regression/basic_x86_linux.o || true
  # Run all non regression with tox
  - tox
after_success:
  - codecov
